# # # # Create the bitbucket-pipelines.yml file
# # # echo "image: node:14
# # # pipelines:
# # #     default:
# # #         - step:
# # #               name: Build and Publish
# # #               caches:
# # #                   - node
# # #               script:
# # #                   - npm install
# # #                   - npm run build
# # #                   - npm run storybook
# # #                   - npm version patch -m \"Bump version to %s\"
# # #                   - npm publish
# # # definitions:
# # #     caches:
# # #         node: ~/.npm" > bitbucket-pipelines.yml

# # image: node:14

# # pipelines:
# #     default:
# #         - step:
# #               name: Build and Publish
# #               caches:
# #                   - node
# #               script:
# #                   - npm install
# #                   - npm run build
# #                   - npm run storybook
# #                   - npm version patch -m \"Bump version to %s\"
# #                   - npm publish
# # definitions:
# #     caches:
# #         node: ~/.npm" > bitbucket-pipelines.yml

# image: node:14

# pipelines:
#     default:
#         - step:
#               name: Build and Publish
#               caches:
#                   - node
#               script:
#                   - npm install
#                   - npm run build
#                   - npm run storybook
#                   - ./bump-version.sh
#                   - npm publish

# definitions:
#     caches:
#         node: ~/.npm

# bitbucket-pipelines.yml

# image: node:14

# pipelines:
#     default:
#         - step:
#               name: Build and Publish
#               caches:
#                   - node
#               script:
#                   - npm install
#                   - npm run build
#                   - npm run storybook
#                   - bash bump-version.sh
#                   - npm publish

# definitions:
#     caches:
#         node: ~/.npm

# bitbucket-pipelines.yml

image: node:14

pipelines:
  default:
    - step:
        name: Build and Publish
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm run storybook
          - bash bump-version.sh
          - npm publish

definitions:
  caches:
    node: ~/.npm
# image: node:14

# pipelines:
#   default:
#     - step:
#         name: Build and Publish
#         caches:
#           - node
#         script:
#           - npm install
#           - npm run build
#           - npm run storybook
#           - echo "Commit author is: $BITBUCKET_COMMIT_AUTHOR"
#           - if [ "$BITBUCKET_COMMIT_AUTHOR" = "Gangavarapu Akarshya" ]; then ./bump-version.sh; fi
#           - npm publish

# definitions:
#   caches:
#     node: ~/.npm
